---
title: "methods-outline"
author: "Cole Brookson"
date: "2/15/2022"
output: word_document
---

# Outline of Proposed Methods

## Our question

### 1) - Is there a relationship between lice on wild fish and lice on farms? 

Need to establish a relationship between a) the number of lice on out-migrating juvenile salmon (DOES THIS NEED TO BE DONE FOR ALL WILD SALMON SPP SEPARATELY? STEPH DID THIS BY LUMPING ALL JUV SALMON IN HER PROC B PAPER) and b) the number of lice on farms. This would need to be done for all years we have both farm data and out migrating lice data. If we can identify a corrlation between the two values higher than some pre-defined threshold (HOW TO CHOOSE THIS? SOME SORT OF R^2 > 0.4?) 

Therefore, we could re-do Marty's PNAS paper analysis looking at the number of lice on farmed fish (THIS WOULD BE WITH BATI DATA?) and then also the amount of lice on out-migrating fish (Steph's Ecol. App. paper) (IS THIS SALMON COAST DATA?)

Then, using the GLMM framework steph has already done in her Proc B paper, we can simply change that to a Bayesian approach, where we have data on the number of lice on fish $i$ in week $j$ of year $k$, in location $q$. So the expected value can be formulated 

$$ \phi(E(Y_{ijkq}|\textbf{X}_{ijkq},b_j,b_q)) \sim \beta_1 \textbf{X}_{ijkq} + (\beta_0 + b_{j,0j} + b_{k,0i})$$


where $\phi$ is the link function, $\beta_1$ is the fixed effect for year and the $b$ values are random intercepts for week ($j$) and location ($q$). Then we define the priors as: 


$$\pi(\beta_0) = N(0,x_1) $$
$$\pi(\beta_1) = N(0,x_2) $$
$$\pi(b_j) = N(0,\tau^2) $$
$$\pi(b_k) = N(0,\tau^2) $$
$$\pi(\tau^2) = IG(0,0.025) $$


So we fit this model for lice on wild fish, get average estimates, then relate that to the data from farm data, and evaluate to see if the correlation is high enough. 

**If the answer to this question is "yes" then we can use data on farmed fish in our next question.**

### 2) Do lice on farmed fish predict returns of wild salmon? 

If lice on farmed fish infect out-migrating juveniles, and subsequently have significant negative effects, then that may affect the returns of those stocks as adults. This can be done with the Ricker model that Steph used, but formulated in a Bayesian framework. Steph's process model for pinks was 
$$ 
\text{ln}\left(\frac{R_{i,t}}{N_{i,t-2}}\right) = r - b_iN_{i,t-2} - cW_{a,t-1} + \theta_i + \theta_{a,t} + \epsilon_{i,t}
$$

$R_{i,t}$ = recruitment of pop $i$ in year $t$, $N_{i,t}$ = abundance os spawners in pop $i$ in year $t-2$, $r$ = growth rate, $b_i$ = density dependence parameter for each pop $i$, $W_{a,t-1}$ = average lice per wild juv. salmon in previous year, $c$ is strength of the relationship between pink salmon survival and lice, $\theta_t$ = spatially coherent variation among *all* pop'ns, $\theta{a,t}$ = spatially coherent variation among pop'ns w/in a management area, and $\epsilon_{i,t}$ is random annual variation independent among populations. (CONFUSED WHY Wt-1? LIKE WHY NOT 2 WOULDN'T THAT BE THE YEAR THAT THE FISH WOULD BE OUT-MIGRATING IF THEY'RE RETURNING AT t AND WERE BORN AT t-2?). This will work for pinks, but not for chum (they're the ones that return at different ages I think). Fleischman et al. (2013) recommends using a state-space Drichlet process to model the variable age at maturity. 

The data in-hand cover the recruitment, the spawner abundance, and then the number of lice on juv. salmon (which we're using farm data for). Parameters to be estimated then are $r$, $b_i$, $c$, and the variances of both $\theta$ values and $\epsilon$. 

**The data required here:**

1) recruitment & spawner data -- PSF (salmon explorer)
    a) this includes harvest data
2) lice on fish data (for first part)
3) lice on farm data (this is available but Cole cannot remember where through)

**To actually do useful things with this model I am suggesting:**

1) Obtain parameter estiamtes for all parameters with all available data
2) Perform a hindcast test with the model using all data up to 2015. Since there is an existing hypothesis of what should happen in 2015, we can see how accurate the model is at predicting that year
3) A leave-one out analysis with important years (likely just do it for all) to see which years may have disproportionate impacts on the dynamics we observe 
4) Cole also wants to do a fun thing and build a S-R package for Julia hehe s