# every parameter that we chose at some given point is defined here 
# because that makes it a bit less stiff overall 


# ---------------------------------------------------------------------------
# Datasets
#
# Each entry becomes a wildcard value {dataset} in the pipeline, and {type} is a 
# second wildcard that the piepline can use
# ---------------------------------------------------------------------------
path:
  raw_fish: "./data/scfs-data/raw/fish-data.csv"
  clean_fish: "./data/scfs-data/clean/standardized-fish-data.csv"
  lice_counts: "./data/scfs-data/clean/lice-counts-for-regression.csv"
  long_lice_counts: "./data/scfs-data/clean/lice-counts-long-form-for-regression.qs2"

# model parameters -------------------------------------------------------------
run:
  motile_only: True 

# # ---------------------------------------------------------------------------
# # Model parameters - one can imagine what these do
# # ---------------------------------------------------------------------------
# model:
#   iter_warmup: 500
#   iter_sampling: 1000
#   chains: 4
#   seed: 42
